# Generated by Django 6.0.6 on 2026-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="country",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("professor", "Professor"),
                    ("vendor", "Vendor"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
