# Generated by Django 6.0.6 on 2026-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                    ("superadmin", "Super Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
