# Generated by Django 6.0.6 on 2026-07-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_vendor_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="books/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
