# Generated by Django 6.0.6 on 2026-07-30 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_book_image_alter_book_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Vendor contact email (falls back to user email)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
