# Generated by Django 6.0.6 on 2026-08-05 15:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_vendor_email_vendor_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="book",
            name="digital_file",
            field=models.FileField(
                blank=True,
                help_text="The digital product file (ebook PDF, notes, template, software archive, etc.)",
                null=True,
                upload_to="products/files/",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="download_expiry_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Number of days the download link is valid after purchase",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="download_limit",
            field=models.PositiveIntegerField(
                default=5, help_text="Maximum number of allowed downloads per purchase"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("ebook", "Ebook"),
                    ("notes", "Lecture Notes"),
                    ("template", "Template"),
                    ("software", "Software"),
                    ("course", "Course Material"),
                ],
                default="ebook",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (e.g. Cloudinary/ImgBB). Takes priority over uploaded image.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("max_downloads", models.PositiveIntegerField(default=5)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="base.book",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="base.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "book", "order")},
            },
        ),
    ]
