# Generated by Django 6.0.6
#
# Safe migration for converting Download from:
#   user + book + order
# to:
#   order_item
#
# Existing Download records are matched to their corresponding OrderItem
# using the existing order + book relationship.

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings


def populate_download_order_items(apps, schema_editor):
    """
    Connect existing Download records to their correct OrderItem.

    Old relationship:
        Download.user
        Download.book
        Download.order

    New relationship:
        Download.order_item
    """

    Download = apps.get_model("base", "Download")
    OrderItem = apps.get_model("base", "OrderItem")

    downloads = Download.objects.all().iterator()

    for download in downloads:
        try:
            order_item = OrderItem.objects.get(
                order_id=download.order_id,
                book_id=download.book_id,
            )
        except OrderItem.DoesNotExist:
            raise RuntimeError(
                f"Could not find OrderItem for Download "
                f"id={download.id}, "
                f"order_id={download.order_id}, "
                f"book_id={download.book_id}."
            )

        download.order_item_id = order_item.id
        download.save(
            update_fields=["order_item"]
        )


def populate_order_item_download_settings(apps, schema_editor):
    """
    Copy the current Book download settings into existing OrderItems.

    This preserves the download rules that existed on the Book at the
    time this migration is run.
    """

    OrderItem = apps.get_model("base", "OrderItem")
    Book = apps.get_model("base", "Book")

    for item in OrderItem.objects.select_related("book").all():
        if item.book:
            item.download_limit = item.book.download_limit
            item.download_expiry_days = item.book.download_expiry_days

            item.save(
                update_fields=[
                    "download_limit",
                    "download_expiry_days",
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0006_remove_book_stock_remove_order_billing_address_and_more",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [

        # ---------------------------------------------------------
        # Existing constraints
        # ---------------------------------------------------------

        migrations.AlterUniqueTogether(
            name="download",
            unique_together=set(),
        ),

        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),

        # ---------------------------------------------------------
        # Book fields
        # ---------------------------------------------------------

        migrations.AddField(
            model_name="book",
            name="cloudinary_public_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=500,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="book",
            name="file_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="book",
            name="file_size",
            field=models.BigIntegerField(
                blank=True,
                editable=False,
                help_text="File size in bytes.",
                null=True,
            ),
        ),

        migrations.AddField(
            model_name="book",
            name="has_digital_file",
            field=models.BooleanField(
                default=False,
                editable=False,
            ),
        ),

        # ---------------------------------------------------------
        # Download fields
        # ---------------------------------------------------------

        migrations.AddField(
            model_name="download",
            name="last_downloaded_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),

        # IMPORTANT:
        # Temporarily nullable so existing records can be populated.
        migrations.AddField(
            model_name="download",
            name="order_item",
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download",
                to="base.orderitem",
            ),
        ),

        # ---------------------------------------------------------
        # OrderItem fields
        # ---------------------------------------------------------

        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="orderitem",
            name="download_expiry_days",
            field=models.PositiveIntegerField(
                default=10,
            ),
        ),

        migrations.AddField(
            model_name="orderitem",
            name="download_limit",
            field=models.PositiveIntegerField(
                default=3,
            ),
        ),

        # ---------------------------------------------------------
        # Book field changes
        # ---------------------------------------------------------

        migrations.AlterField(
            model_name="book",
            name="digital_file",
            field=models.FileField(
                blank=True,
                help_text="Private ebook/document file.",
                null=True,
                upload_to="ebooks/",
            ),
        ),

        migrations.AlterField(
            model_name="book",
            name="download_expiry_days",
            field=models.PositiveIntegerField(
                default=10,
                help_text=(
                    "Number of days download access remains valid "
                    "after purchase."
                ),
            ),
        ),

        migrations.AlterField(
            model_name="book",
            name="download_limit",
            field=models.PositiveIntegerField(
                default=3,
                help_text=(
                    "Maximum downloads allowed per purchased item."
                ),
            ),
        ),

        migrations.AlterField(
            model_name="book",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL.",
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="download",
            name="max_downloads",
            field=models.PositiveIntegerField(
                default=3,
            ),
        ),

        # ---------------------------------------------------------
        # Copy Book download settings -> OrderItem
        # ---------------------------------------------------------

        migrations.RunPython(
            populate_order_item_download_settings,
            migrations.RunPython.noop,
        ),

        # ---------------------------------------------------------
        # Connect existing Downloads -> OrderItems
        # ---------------------------------------------------------

        migrations.RunPython(
            populate_download_order_items,
            migrations.RunPython.noop,
        ),

        # ---------------------------------------------------------
        # Now that every Download has an OrderItem,
        # make the relationship required.
        # ---------------------------------------------------------

        migrations.AlterField(
            model_name="download",
            name="order_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download",
                to="base.orderitem",
            ),
        ),

        # ---------------------------------------------------------
        # OrderItem unique constraint
        # ---------------------------------------------------------

        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "book"),
                name="unique_book_per_order",
            ),
        ),

        # ---------------------------------------------------------
        # Download indexes
        # ---------------------------------------------------------

        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["product_type"],
                name="base_book_product_b6f705_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["user"],
                name="base_downlo_user_id_c08d25_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["expires_at"],
                name="base_downlo_expires_31cb1a_idx",
            ),
        ),

        # ---------------------------------------------------------
        # Remove old Download relationships
        # ---------------------------------------------------------

        migrations.RemoveField(
            model_name="download",
            name="book",
        ),

        migrations.RemoveField(
            model_name="download",
            name="order",
        ),
    ]